// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ9me-LxjzdfNedbUamu7a9Jh077eBYDA',
    appId: '1:960792720630:web:652a68e78a6444a8fb28d7',
    messagingSenderId: '960792720630',
    projectId: 'finance-management-app-30b1f',
    authDomain: 'finance-management-app-30b1f.firebaseapp.com',
    storageBucket: 'finance-management-app-30b1f.appspot.com',
    measurementId: 'G-2T4FB50P4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBCYQFEDMEuHNHMnolUkaI-tvT2xpAbmY',
    appId: '1:960792720630:android:490aa466ee546a40fb28d7',
    messagingSenderId: '960792720630',
    projectId: 'finance-management-app-30b1f',
    storageBucket: 'finance-management-app-30b1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoRNlEw7BKjZASJxa4_rYKA9uKDz748o',
    appId: '1:960792720630:ios:6a1d552a10d3268cfb28d7',
    messagingSenderId: '960792720630',
    projectId: 'finance-management-app-30b1f',
    storageBucket: 'finance-management-app-30b1f.appspot.com',
    androidClientId: '960792720630-9470986pabpf6e7n5en1rgkoss5kpear.apps.googleusercontent.com',
    iosClientId: '960792720630-e6r3o28ch3tfeo864vvm73q9bi1aa9tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.managment',
  );
}
